### ISSUE TITLE
run multiple GPUs

### ISSUE THREAD

**Issue by slsdilei** [DearCaat/RRT-MIL#3]
Hi, Dr.how can I set multiple GPUs to run?

**Comment by DearCaat** [comment]
Good question...
In fact, the `batch size` for WSI classification is all `1`, because each bag contains a different number of instances. I have not tried any kind of multi-host or multi-GPU training in WSI classification. Maybe `torch.nn.DataParallel` is an ok solution? 
I'm not quite sure, sorry, it may take some attempts.

**Comment by slsdilei** [comment]
> 好问题... 事实上，`batch size`WSI 的分类是全部`1`，因为每个包都包含不同数量的实例。我还没有在 WSI 分类中尝试过任何类型的多主机新生儿 GPU 训练。也许`torch.nn.DataParallel`是一个好的解决方案我不太 确定，抱歉，可能需要一些尝试。

Okay,Thank you for your reply.
I can run on a TiTanX 12GB memory. But if I run on a 3070, 8GB of memory is not enough

Error: CUDA out of memory
