### ISSUE TITLE
Labels for cancer subtyping

### ISSUE THREAD

**Issue by JackyC666** [DearCaat/RRT-MIL#8]
Hi, How did you label the BRCA dataset? In your paper,
```
TCGA-BRCA includes two sub-types of cancers, Inva-
sive Ductal Carcinoma (IDC) and Invasive Lobular Carci-
noma (ILC). There are 779 IDC slides and 198 ILC slides.
```
So, HOW can I REPEAT it?
In the TCGA DATASET，I can`t found something about it!
Thanks~~

**Comment by DearCaat** [comment]
I got these labels from the `manifest` file obtained from the `GDC` website, specifically:

- I first downloaded the `manifest` file under `Diagnostic Slide` of `TCGA-BRCA` project from the GDC official website.
- Second, I obtained the `case_id` and `primary_diagnosis` fields for each case from that file.
- Finally, I classified the `primary_diagnosis` field containing the IDC or ILC subtype keyword as either IDC or ILC. Thus, I got the BRCA labels that I am using now.

Since I haven't found any other way to process this either, I'm not sure if this is entirely appropriate, so if you have a better idea, feel free to leave a comment.

**Comment by JackyC666** [comment]
> I got these labels from the `manifest` file obtained from the `GDC` website, specifically:
> 
> * I first downloaded the `manifest` file under `Diagnostic Slide` of `TCGA-BRCA` project from the GDC official website.
> * Second, I obtained the `case_id` and `primary_diagnosis` fields for each case from that file.
> * Finally, I classified the `primary_diagnosis` field containing the IDC or ILC subtype keyword as either IDC or ILC. Thus, I got the BRCA labels that I am using now.
> 
> Since I haven't found any other way to process this either, I'm not sure if this is entirely appropriate, so if you have a better idea, feel free to leave a comment.

Thanks for your reply!
where is the ```primary_diagnosis```? 
Can you give me a link?  
Or a screenshot to illustrate?
Sincerely thank you for your help!

**Comment by DearCaat** [comment]
Sorry, it's a file named `clinical.json`, and it's also downloaded on GDC site. The `praimary_diagnosis` is one field of this json file, like this: 
![image](https://github.com/DearCaat/RRT-MIL/assets/33518172/d74c89ba-6551-4680-959a-0eb77414bf16)
